services:
  - type: web
    name: AI-Medical-Chatbot
    env: node
    plan: free

    rootDir: backend

    buildCommand: npm install && pip3 install -r ../requirements.txt

    startCommand: node server.js

    envVars:
      - key: GROQ_API_KEY
        sync: false
